# copy of docker running
sudo: required
# build image
services:
  - docker

# run test suite with dev.Dockerfile - test files and suite
before_install:
  - docker build -t azrielh/docker-react -f dev.Dockerfile .
# how to deploy to aws

script:
  - docker run azrielh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-386537467856"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
